@isTest
class testOrgRelationships {
     static testMethod void testTrigger() {/*
         Account a1 = new Account(Name = 'Account 1');
         insert a1;         
         Account a2 = new Account(Name = 'Account 2');
         insert a2;         
         givingpower__Organization_Relationship__c OrgRel = new givingpower__Organization_Relationship__c(givingpower__Account__c = a1.Id, givingpower__Related_Account__c = a2.Id, givingpower__Status__c = 'Current', givingpower__Type__c = 'Partner', givingpower__Description__c = 'Description');
         insert OrgRel;
         OrgRel.givingpower__Description__c = 'adsasdasdsad';
         update OrgRel;
         delete OrgRel;*/
     }
}